# JSON to DOT Converter Configuration
app:
  name: JSON to DOT Converter
  version: 1.0.0
  
# Diagram generation settings
diagram:
  # Default diagram settings
  settings:
    rankdir: TB
    node-defaults:
      fontname: Arial
      shape: none
  
  # Template settings
  templates:
    base-path: classpath:/templates/
    entity-template: entity.vm
    relationship-template: relationship.vm
    main-template: diagram.vm
    
  # Style configuration
  styles:
    # Default styles for all entities
    default:
      header:
        bgcolor: "#333333"
        forecolor: white
        font: Arial
        font-size: 12
        bold: true
      body:
        bgcolor: "#FFFFFF"
        forecolor: "#000000"
        font: Arial
        font-size: 10
      separator:
        color: "#333333"
      mandatory:
        bgcolor: "#FFFFFF"
        forecolor: "#DC2626"
        font: Arial
        font-size: 10
        bold: true
      special-section:
        bgcolor: "#FFFFFF"
        forecolor: "#DC2626"
        font: Arial
        font-size: 10
        bold: true
      constraint:
        bgcolor: "#F5F5F5"
        forecolor: "#666666"
        font: Arial
        font-size: 9
      relationship:
        color: "#666666"
        font-size: 9
        style: solid
    
    # Entity-specific overrides
    entities:
      # Request entities (blue theme)
      carrier:
        header:
          bgcolor: "#1E3A8A"
          forecolor: white
        body:
          bgcolor: "#E0F2FE"
          
      shipper:
        header:
          bgcolor: "#1E3A8A"
          forecolor: white
        body:
          bgcolor: "#E0F2FE"
 #########################################################################
 #   PARTY
 #########################################################################
      party:
        header:
          bgcolor: "#004030"
          forecolor: white
        body:
          bgcolor: "#4A9782"
        separator:
          color: "#DCD0A8"
      party_version:
        header:
          bgcolor: "#004030"
          forecolor: white
        body:
          bgcolor: "#4A9782"
        separator:
          color: "#DCD0A8"
      party_operation:
        header:
          bgcolor: "#004030"
          forecolor: white
        body:
          bgcolor: "#4A9782"
        separator:
          color: "#DCD0A8"
      party_finance:
        header:
          bgcolor: "#004030"
          forecolor: white
        body:
          bgcolor: "#4A9782"
        separator:
          color: "#DCD0A8"
      party_bank_information:
        header:
          bgcolor: "#004030"
          forecolor: white
        body:
          bgcolor: "#4A9782"
        separator:
          color: "#DCD0A8"
      certification:
        header:
          bgcolor: "#004030"
          forecolor: white
        body:
          bgcolor: "#4A9782"
        separator:
          color: "#DCD0A8"
      party_payment_methods:
        header:
          bgcolor: "#004030"
          forecolor: white
        body:
          bgcolor: "#4A9782"
        separator:
          color: "#DCD0A8"

#########################################################################
#   PRODUCT
#########################################################################
      product:
        header:
          bgcolor: "#57564F"
          forecolor: white
        body:
          bgcolor: "#DDDAD0"
        separator:
          color: "#DDDAD0"
      product_version:
        header:
          bgcolor: "#57564F"
          forecolor: white
        body:
          bgcolor: "#DBEAFE"
        separator:
          color: "#DDDAD0"
      product_dimensions:
        header:
          bgcolor: "#57564F"
          forecolor: white
        body:
          bgcolor: "#DBEAFE"
        separator:
          color: "#DDDAD0"
      product_category:
        header:
          bgcolor: "#57564F"
          forecolor: white
        body:
          bgcolor: "#DBEAFE"
        separator:
          color: "#DDDAD0"
      inventory_policy:
        header:
          bgcolor: "#57564F"
          forecolor: white
        body:
          bgcolor: "#DBEAFE"
        separator:
          color: "#DDDAD0"
      product_logistics:
        header:
          bgcolor: "#57564F"
          forecolor: white
        body:
          bgcolor: "#DBEAFE"
        separator:
          color: "#DDDAD0"
      product_specification:
        header:
          bgcolor: "#57564F"
          forecolor: white
        body:
          bgcolor: "#DBEAFE"
        separator:
          color: "#DDDAD0"
#########################################################################
#   LOCATION
#########################################################################
      location:
          header:
            bgcolor: "#4DA8DA"
            forecolor: white
          body:
            bgcolor: "#FEF2F2"
          separator:
            color: "#F5F5F5"
      location_version:
          header:
            bgcolor: "#4DA8DA"
            forecolor: white
          body:
            bgcolor: "#FEF2F2"
          separator:
            color: "#F5F5F5"
      address:
          header:
            bgcolor: "#4DA8DA"
            forecolor: white
          body:
            bgcolor: "#FEF2F2"
          separator:
            color: "#F5F5F5"
      location_details:
          header:
            bgcolor: "#4DA8DA"
            forecolor: white
          body:
            bgcolor: "#FEF2F2"
          separator:
            color: "#F5F5F5"
#########################################################################
#   CONTACT
#########################################################################
      contact:
        header:
          bgcolor: "#1B3C53"
          forecolor: white
        body:
          bgcolor: "#D1FAE5"
        separator:
          color: "#F9F3EF"
      contact_version:
        header:
          bgcolor: "#1B3C53"
          forecolor: white
        body:
          bgcolor: "#D1FAE5"
        separator:
          color: "#F9F3EF"
#########################################################################
#   COMMON
#########################################################################
      tag:
        header:
          bgcolor: "#4B352A"
          forecolor: white
        body:
          bgcolor: "#FEF3C7"
        separator:
          color: "#F0F2BD"
      geo_fence_point:
        header:
          bgcolor: "#4B352A"
          forecolor: white
        body:
          bgcolor: "#FEF3C7"
        separator:
          color: "#F0F2BD"
      custom_field:
        header:
          bgcolor: "#4B352A"
          forecolor: white
        body:
          bgcolor: "#FEF3C7"
        separator:
          color: "#F0F2BD"
      business_timing:
        header:
          bgcolor: "#4B352A"
          forecolor: white
        body:
          bgcolor: "#FEF3C7"
        separator:
          color: "#F0F2BD"
#########################################################################
#   RATE
#########################################################################
      contract:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"

      service_type:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"

      service_commitment:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"

      
      # Rate entities (orange theme)
      rate:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"
          
      # Rate type entities (purple theme)
      rate_type:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"
          
      # Rate break entities (pink theme)
      rate_break:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"
      
      # Terms entities (brown theme)
      demurrage_rates:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"
          
      demurrage_rates_break:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"
          
      detention_rates:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"
          
      detention_rates_break:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"
          
      contract_charge:
        header:
          bgcolor: "#722323"
          forecolor: white
        separator:
          color: "#FFECCC"
          


# Logging configuration
logging:
  level:
    com.example.converter: INFO
    org.springframework.boot: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
# Spring Boot CLI configuration
spring:
  main:
    web-application-type: none
    banner-mode: off
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL